version: "3.2"
networks:
  webappnetwork:
    driver: bridge
services:
  client:
    build:
      context: ./client
    ports:
      - "80:80"
      - "443:443"
      - "3000:3000"
    volumes:
      - ./client:/client
      - /client/node_modules
    links:
      - api
    networks:
      - webappnetwork
  api:
    build:
      context: ./api
    ports:
      - "9000:9000"
    volumes:
      - ./api:/api
      - /api/node_modules
    depends_on:
      - mongodb
    networks:
      - webappnetwork
  mongodb:
    image: mongo:4.0
    restart: always
    container_name: mongodb
    volumes:
      - "data-node:/data/db"
    ports:
      - 27017:27017
    command: mongod --noauth --smallfiles
    networks:
      - webappnetwork
# Run this before : docker volume create --name=data-node
volumes:
  data-node:
   external: true
